kind: pipeline
type: docker
name: ScienceQuestAndroid

trigger:
  branch:
    - Android
  event:
    - push

steps:
  - name: code-analysis-android
    image: aosapps/drone-sonar-plugin
    settings: 
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token