kind: pipeline
type: docker
name: ScienceQuestPhp

trigger:
  branch:
    - php
  event:
    - push

steps:
  - name: code-analysis-php
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_sae_token