kind: pipeline
type: docker
name: ScienceQuestAPI

trigger:
  branch:
    - Springboot
  event:
    - push

services:
  postgres_server:
    image: postgres:16-alpine
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_PASSWORD:
        from_secret: postgres_password_secret
      POSTGRES_USER: ScienceQuest
      POSTGRES_DB: ScienceQuest

  adminer:
    image: adminer
    depends_on:
      - postgres_server
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres_server
    ports:
      - "8080:8080"

steps:
  - name: build_app
    image: maven:3-eclipse-temurin-21-alpine
    settings:
      context: SpringBootProject/
    commands:
      - sed -i -e "s/localhost/postgres_server/g" src/main/resources/application.properties
      - echo 'server.port=80' >> src/main/resources/application.properties
      - mvn clean package

  - name: run_app
    image: openjdk:21-slim
    depends_on:
      - build_app
    settings:
      context: SpringBootProject/
    commands:
      - java -jar target/sae-0.0.1-SNAPSHOT.jar
