kind: pipeline
type: docker
name: ScienceQuestAPI

trigger:
  branch:
    - Springboot
  event:
    - push

steps:
  - name: deploy-container-postgresql
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
        IMAGENAME: postgres:16-alpine
        CONTAINERNAME: postgres_server
        COMMAND: create
        OVERWRITE: true
        PRIVATE: true
        CODEFIRST_CLIENTDRONE_ENV_POSTGRES_PASSWORD:
          from_secret: postgres_password_secret
        CODEFIRST_CLIENTDRONE_ENV_POSTGRES_DB: ScienceQuest
        CODEFIRST_CLIENTDRONE_ENV_POSTGRES_USER: ScienceQuest
        ADMINS: alixjeudi--lemoine,victorsoulier,gwenaelplanchon

  - name: build-app
    image: maven:3-eclipse-temurin-21-alpine
    depends_on: [deploy-container-postgresql]
    commands:
      - cd SpringBootProject/
      - sed -i -e "s/localhost/tombiard-postgres_server/g" src/main/resources/application.properties
      - echo -e "\nserver.port=443\nserver.forward-headers-strategy=framework" >> src/main/resources/application.properties
      - mvn clean package
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://tombiard-postgres_server:5432/ScienceQuest
      SPRING_DATASOURCE_USERNAME: ScienceQuest
      SPRING_DATASOURCE_PASSWORD: 
        from_secret: postgres_password_secret

#  - name: deploy-container-adminer
#    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
#    environment:
#        IMAGENAME: adminer:latest
#        CONTAINERNAME: adminer
#        COMMAND: create
#        OVERWRITE: true
#        CODEFIRST_CLIENTDRONE_ENV_ADMINER_DEFAULT_SERVER: postgres_server
#        ADMINS: alixjeudi--lemoine,victorsoulier,gwenaelplanchon

  - name: build-container-app-image
    image: plugins/docker
    depends_on: [build-app]
    settings:
      dockerfile: Dockerfile
      registry: hub.codefirst.iut.uca.fr
      repo: hub.codefirst.iut.uca.fr/alix.jeudi--lemoine/api
      username:
        from_secret: SECRET_REGISTRY_USERNAME
      password:
        from_secret: SECRET_REGISTRY_PASSWORD

  - name: deploy-container-app
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    depends_on: [build-container-app-image,deploy-container-postgresql]
    environment:
      IMAGENAME: hub.codefirst.iut.uca.fr/alix.jeudi--lemoine/api:latest
      CONTAINERNAME: api
      COMMAND: create
      OVERWRITE: true
      CODEFIRST_CLIENTDRONE_ENV_SPRING_DATASOURCE_URL: jdbc:postgresql://tombiard-postgres_server:5432/ScienceQuest
      CODEFIRST_CLIENTDRONE_ENV_SPRING_DATASOURCE_USERNAME: ScienceQuest
      CODEFIRST_CLIENTDRONE_ENV_SPRING_DATASOURCE_PASSWORD: 
        from_secret: postgres_password_secret
      ADMINS: alixjeudi--lemoine,victorsoulier,gwenaelplanchon

  - name: code-analysis-android
    image: aosapps/drone-sonar-plugin
    settings: 
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_sae_token